server:
  port: 80


spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      host: 192.168.124.33
      port: 8500
      discovery:
        service-name: ${spring.application.name}
#        prefer-ip-address: true
#        ip-address: 192.168.124.1
#        health-check-url: http://192.168.124.1:80/actuator/health
        health-check-url: http://192.168.124.33:8500